# Generated by Django 5.2.17 on 2026-10-02 20:04

import django.core.validators
import parties.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, validators=[parties.validators.validate_national_code])),
                ('commission', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict, validators=[parties.validators.validate_details])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'label'],
                'constraints': [models.UniqueConstraint(fields=('name', 'label'), name='uniq_party_name_label'), models.UniqueConstraint(condition=models.Q(('national_code__isnull', False)), fields=('national_code',), name='uniq_party_national_code')],
            },
        ),
    ]
