# Generated by Django 5.2.17 on 2026-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
