# Generated by Django 5.2.17 on 2026-10-02 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='parties.party'),
        ),
        migrations.AddField(
            model_name='load',
            name='tare_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
