# Generated by Django 5.2.17 on 2026-10-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tare_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('image_updated_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
    ]
