# Generated by Django 5.2.17 on 2026-10-02 20:20

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background',
            field=models.CharField(blank=True, default='', max_length=7, validators=[catalog.validators.validate_background]),
        ),
        migrations.AddField(
            model_name='product',
            name='sticker',
            field=models.CharField(blank=True, default='', max_length=40, validators=[catalog.validators.validate_sticker]),
        ),
    ]
